# - name: Import Google Chrome GPG signing key
#   apt_key:
#     url: https://dl-ssl.google.com/linux/linux_signing_key.pub
#     state: present
#     id: 7FAC5991

# - name: Add Google Chrome key
#   shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#   when: google_apt_exists.rc == 1

# - name: Add Google Chrome x86_64 repository
#   apt_repository:
#     repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
#     state: present
#   when: ansible_architecture == 'x86_64'

# - name: Install Google Chrome
#   apt: pkg=google-chrome-stable state=latest update_cache=yes cache_valid_time=3600
#   register: google_chrome_install

#   - name: Add Chrome signing key
#   become: true
#   apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
#            state=present
#            validate_certs=true

# - name: Add Chrome repo
#   become: true
#   apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
#                   state=present
