- hosts: localhost local element env gthinkpad
#  become: true
  become: yes
  become_method: su
  remote_user: root
  become_user: root

  tasks:
    - include: roles/common/tasks/update.yml
    - include: roles/common/tasks/upgrade.yml
#    - include: roles/common/tasks/repo/chrome.yml
#    - include: roles/common/tasks/repo/typora.yml
#    - include: roles/common/tasks/repo/all-combined.yml
    - include: roles/common/tasks/apt-install.yml
#    - include: roles/common/tasks/pip.yml
#    - include: roles/common/tasks/snap/google-play.yml
#    - include: roles/common/tasks/spideroak.yml
    - include: roles/common/tasks/repo/sublimetext.yml
#    - include: roles/common/tasks/tlp.yml
    - include: roles/common/tasks/upgrade.yml
    - include: roles/common/tasks/cleanup.yml
    - include: roles/common/tasks/ssh-permissions.yml
    - include: roles/common/tasks/bash.yml
    - include: roles/common/tasks/vim-runtime.yml
    - include: roles/common/tasks/vim.yml