- hosts: localhost local element env
  become: true
  become_user: root

  tasks:
    # - include: tasks/dropbox-setup.yml
    - include: tasks/update.yml
    - include: tasks/upgrade.yml
    - include: tasks/cleanup.yml
    - include: tasks/repo/all-combined.yml
    - include: tasks/apt-install.yml
